media:
  - name: documents
    input: src/media/documents
    output: /media/documents
    categories: [ document ]
  - name: images
    input: src/media/images
    output: /media/images
    categories: [ image ]
content:
  