media:
  - name: documents
    input: src/media/documents
    output: /media/documents
    categories: [ document ]
  - name: images
    input: src/media/images
    output: /media/images
    categories: [ image ]
content:
  - name: node_descriptions
    type: collection
    path: src/md/nodes
    fields:
      - name: title
        label: Title of the node entry
        type: text
        default: Node title
        hidden: true
        required: true
      - name: summary
        label: Single sentence summary
        type: text
        required: true
      - name: tool_list_proprietary
        label: Related proprietary tools and components
        type: reference
        options:
          collection: tools_proprietary
          multiple: true
          search: "name,vendor"
          value: "{id}"
          label: "{name} ({vendor})"
      - name: tool_list_open_source
        label: Related open source tools and components
        type: reference
        options:
          collection: tools_open_source
          multiple: true
          search: "name,vendor"
          value: "{id}"
          label: "{name} ({vendor})"
  - name: tools_proprietary
    type: collection
    path: src/md/tools/proprietary
    fields:
      - name: name
        label: Name of the tool or component
        type: text
        required: true
      - name: vendor
        label: Vendor
        type: text
        required: true
      - name: links
        label: Related links
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
        list: true
  - name: tools_open_source
    type: collection
    path: src/md/tools/open_source
    fields:
      - name: name
        label: Name of the tool or component
        type: text
        required: true
      - name: repository
        label: Link to the repository
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
        required: true
      - name: links
        label: Other related links
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
        list: true
      
        