media:
  - name: documents
    input: media/documents
    output: /media/documents
    categories: [ document ]
  - name: images # Note: 'name' key is required here
    input: media/images
    output: /media/images
    categories: [ image ]