media:
  - name: files
    input: src/media/files
    output: /media/files
    categories: [ document, video, audio, compressed ]
  - name: images
    input: src/media/images
    output: /media/images
    categories: [ image ]
content:
  - name: nodes
    label: Flow chart nodes
    type: collection
    path: src/md/nodes
    subfolders: false
    filename: "{fields.title}.md"
    fields:
      - name: title
        label: Title of the node entry
        type: text
        default: Node title
        hidden: true
        required: true
      - name: summary
        label: Single sentence summary
        type: text
        required: true
      - name: links
        label: Related links
        component: link
        list: true
      - name: tool_list_proprietary
        label: Related proprietary tools and components
        type: reference
        options:
          collection: tools_proprietary
          multiple: true
          search: "name,vendor"
          value: "{id}"
          label: "{name} ({vendor})"
      - name: tool_list_open_source
        label: Related open source tools and components
        type: reference
        options:
          collection: tools_open_source
          multiple: true
          search: "name,vendor"
          value: "{id}"
          label: "{name} ({vendor})"
  - name: tools_proprietary
    label: Proprietary tools and components
    type: collection
    path: src/md/tools/proprietary
    filename: "{fields.name}.md"
    subfolders: false
    fields:
      - name: name
        label: Name of the tool or component
        type: string
        required: true
      - name: vendor
        label: Vendor
        type: text
        required: true
      - name: links
        label: Related links
        component: link
        list: true
      - name: description
        label: Description
        component: main_description
  - name: tools_open_source
    label: Open source tools and components
    type: collection
    path: src/md/tools/open_source
    filename: "{fields.name}.md"
    subfolders: false
    fields:
      - name: name
        label: Name of the tool or component
        type: string
        required: true
      - name: repository
        label: Link to the repository
        component: link
        required: true
      - name: links
        label: Other related links
        component: link
        list: true
      - name: description
        label: Description
        component: main_description
  - name: projects
    label: Research projects
    type: collection
    path: src/md/projects
    filename: "{fields.acronym}.md"
    subfolders: false
    fields:
      - name: acronym
        label: Acronym
        type: string
        required: true
      - name: full_title
        label: Full title
        type: string
        required: false
      - name: links
        label: Links
        component: link
        required: true
      - name: duration
        label: Project duration
        component: duration
        required: true
      - name: description
        label: Project description
        component: main_description
        required: false
components:
  link:
    type: string
    pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
  main_description:
    type: rich-text
    description: Full description
    options:
      media: true
  duration:
    type: object
    fields:
      - name: start_date
        label: Start date
        type: date
      - name: end_date
        label: End date
        type: date
settings:
  hide: false
  content:
    merge: true
  

      
        